### ISSUE TITLE
Eres o no eres ?

### ISSUE THREAD

**Issue by danielex1999** [Roman31X/Java_POO#1]
Ya pero eres o no eres ?
![image](https://github.com/Roman31X/Java_POO/assets/69739890/11aa7809-289c-4a10-b25d-ee08d24641c4)

**Comment by ghost** [comment]
LGTM
![image](https://github.com/Roman31X/Java_POO/assets/44541612/969cfa28-0a02-451a-a8d8-4026d1e4b387)

**Comment by danielex1999** [comment]
Cerrando el caso
Diego es :v
